---
- hosts: local
  roles:
    - role: mcenirm.postgresql94-server

- hosts: local
  vars:
    df_version: "2.2.0"
    remi_release_rpm: "remi-release-7.1-3.el7.remi.noarch.rpm"
  tasks:
    - name: "Download (pre)"
      with_items: []
      get_url:
        dest: "{{ dist_dir ~ '/' ~ (item.file | default(item.url | basename)) }}"
        url: "{{ item.url }}"
    - name: "Download"
      with_items:
        - url: "{{ 'http://rpms.famillecollet.com/enterprise/7/safe/x86_64/' ~ remi_release_rpm }}"
          sha256: "54845185f04095145798295f54ef9f6f3838ea7e13a93d99c3080c9126693773"
        - url: "{{ 'https://github.com/dreamfactorysoftware/dreamfactory/archive/' ~ df_version ~ '.tar.gz' }}"
          file: "{{ 'dreamfactory-' ~ df_version ~ '.tar.gz' }}"
          sha256: "d0a02bb63447aea71ced9274335fec65346c0a4e9e51c4adcb16e4a204b551cc"
      get_url:
        checksum: "{{ 'sha256:' ~ item.sha256 | default(omit) }}"
        dest: "{{ dist_dir ~ '/' ~ (item.file | default(item.url | basename)) }}"
        url: "{{ item.url }}"
    - name: "Remi repo"
      yum:
        name: "{{ dist_dir ~ '/' ~ remi_release_rpm }}"
        state: present

    - name: "PHP 7.0"
      with_items:
        - "php70"
        - "php70-build"
        - "php70-php"
        - "php70-php-devel"
        - "php70-php-mysqlnd"
        - "php70-php-pgsql"
      yum:
        name: "{{ item }}"
        state: present
