---
- hosts: local
  roles:
    - role: mcenirm.postgresql94-server
    - role: mcenirm.php70

- hosts: local
  vars:
    df_version: "2.2.0"
  tasks:
    - name: "Download (pre)"
      with_items: []
      get_url:
        dest: "{{ dist_dir ~ '/' ~ (item.file | default(item.url | basename)) }}"
        url: "{{ item.url }}"
    - name: "Download"
      with_items:
        - url: "{{ 'https://github.com/dreamfactorysoftware/dreamfactory/archive/' ~ df_version ~ '.tar.gz' }}"
          file: "{{ 'dreamfactory-' ~ df_version ~ '.tar.gz' }}"
          sha256: "d0a02bb63447aea71ced9274335fec65346c0a4e9e51c4adcb16e4a204b551cc"
      get_url:
        checksum: "{{ 'sha256:' ~ item.sha256 | default(omit) }}"
        dest: "{{ dist_dir ~ '/' ~ (item.file | default(item.url | basename)) }}"
        url: "{{ item.url }}"
